### ISSUE TITLE
Ammo Spacing Discrepancies & Scoreboard Survivor Health

### ISSUE THREAD

**Issue by teigrgwyn** [l4d/hud#7]
I can see great potential here, please carry on with the updates.

Issue 1:
There is about a 10px difference for the primary and reserve ammo spacing. With pistols out, the ammo appears more to the right than it should be, and the primary ammo is slightly closer to the reserve ammo than primary weapons. I'm not sure if you care about it, but if you switch weapons a lot, it can be distracting.

Issue 2:
Perhaps you could overlay a half-opaque rectangle underneath the survivor health on the scoreboard? The white health bar will go down while the darker one underneath remains static, so it's easier to tell how much health they have when their health depletes. Otherwise, you don't really have any clue what their maximum health is supposed to be, so it can be much more difficult to gauge their health than it needs to be. (I don't know if you've actually started working on the scoreboard yet, however.)
![scoreboard-health](https://cloud.githubusercontent.com/assets/15336751/12292504/52fe80ea-b9a2-11e5-9f2e-45caaf053694.jpg)

Suggestion 1:
Everything is giving off a metro-like minimalist "design" vibe, but the Windows XP style pill icon is messing it up with it's hard rectangle nature.
![pill-design](https://cloud.githubusercontent.com/assets/15336751/12292521/7476b468-b9a2-11e5-962e-71cbfc0ff4f5.png)
Perhaps something that is more appealing, such as a pill? I know there's too much going on for it to be like this, but whatever you want to go with.
![pill](https://cloud.githubusercontent.com/assets/15336751/12292384/87ccb7de-b9a1-11e5-9316-489c747819cf.png)

Also, if you need any help, just let me know. I'm interested. :+1:

**Comment by l4d** [comment]
Issue 1 is due to a panel animation. The stock hud has a grow animation when switching between weapons that I believe is hard coded in the game. The panels are still there, just hidden. That's why you still see the slight shift when switching weapons.

Issue 2 will  be fixed when I work on redesigning the scoreboard.

As for the suggestion, I actually have a few different variants of the icon sets I will eventually share in the future. This is so people can choose the style they prefer. You can see some alt styled sets below:
![alternates](https://cloud.githubusercontent.com/assets/14987789/12313005/fb50eadc-ba31-11e5-80d9-cd44a8400cf0.png)

**Comment by teigrgwyn** [comment]
Is it possible to have a choice of a type of health bar that wraps around the icons, something like this?
![health-bar](https://cloud.githubusercontent.com/assets/15336751/12314415/c941d15c-ba25-11e5-9e52-487d1373eb2a.png)
Or a gray & darker gray, etc.

**Comment by l4d** [comment]
Technically, no. The base healthbar texture is locked and doesn't respond to edits. It is possible in L4D2, as the texture isn't locked and they also provided a tick health texture. If you really wanted to, you could put something together that resembles that in L4D1, but you would lose some of the functionality of the healthbar. It would just be a solid colored textured that shows green, yellow, and red.
